### ISSUE TITLE
Generate FlatBufferBuilder extension which enable user to build byte array without object allocation

### ISSUE THREAD

**Issue by mzaks** [mzaks/FlatBuffersSwift#13]

**Comment by hassila** [comment]
Wouldn't it make sense to have the same struct approach as for decoding (i.e. value-based) for this?

Sampling the generation code, the majority is simply object creation/destruction...

**Comment by mzaks** [comment]
I am thinking about having static functions on Fast structs which will get a buffer and all the values and pointers, but I am not 100% certain yet how it should look like
