### ISSUE TITLE
Support mutable computed properties easy modification

### ISSUE THREAD

**Issue by hassila** [mzaks/FlatBuffersSwift#17]
The current lazy property API is read-only, but if moving to computed properties as suggested in https://github.com/mzaks/FlatBuffersSwift/issues/16, I think it would also make sense to allow such instances to be mutable.

Either the setter can modify the backing store directly, or if actual space requirements changes, a separate map of changes can be kept and used for serialization purposes (in those cases a new buffer would need to be generated, similar to how the convenience "eager" object works today).

This way, one could keep essentially zero-copy operation for both reading/building for many common interesting cases and retain an easy-to-use API also for such use cases.

**Comment by hassila** [comment]
I guess this may also be related to/solving https://github.com/mzaks/FlatBuffersSwift/issues/13

**Comment by mzaks** [comment]
This is slightly different approach #13 is about building a new buffer with copying values. this one would allow user build a buffer once and than update scalar values in place. In C++ implementation of FlatBuffers they call it Reflection API as far as I know.

**Comment by mzaks** [comment]
Mutation of Scalar properties is already implemented, I will also provide a possibility to mutate scalars inside of a Vector
