### ISSUE TITLE
Structs embedded in structs does not work

### ISSUE THREAD

**Issue by hassila** [mzaks/FlatBuffersSwift#18]
I had a look at implementing the benchmark used by google for flat buffers using the .fbs from https://github.com/google/flatbuffers/blob/benchmarks/benchmarks/cpp/FB/bench.fbs 

This yielded an empty struct 'Foo' when processed thusly:

`solid:FlatBuffersPerformanceTestDesktop jocke$ java -jar ../fbsCG.jar -fbs bench.fbs -out bench.swift -lang swift
ERROR (org.eclipse.xtext.diagnostics.Diagnostic.Syntax) 'mismatched input 'id' expecting '}'' on Struct maxim.zaks.flatBuffers.impl.StructImpl@3301500b (name: Foo), lineNumber 25, length 2

'bench.swift' has been generated.
 `

Attaching the generated swift file as well.
[bench.swift.txt](https://github.com/mzaks/FlatBuffersSwift/files/237122/bench.swift.txt)

**Comment by mzaks** [comment]
Yes indeed I will bundle it together with 
Support memory alignment #4
Where I have to compute struct length dependent on memory alignment.

**Comment by mzaks** [comment]
Should actually work now, I just didn't test it yet

**Comment by hassila** [comment]
I gave it a try (just change foo and bar to struct to match the original .fbs), but no go yet:

```
solid:FlatBuffersSwift jocke$ java -jar fbsCG.jar -fbs FlatBuffersPerformanceTestDesktop/bench.fbs -out FlatBuffersPerformanceTestDesktop/bench.swift -lang swift -lib exclude
ERROR (org.eclipse.xtext.diagnostics.Diagnostic.Syntax) 'mismatched input 'id' expecting '}'' on Struct maxim.zaks.flatBuffers.impl.StructImpl@3a45c42a (name: Foo), lineNumber 26, length 2

'FlatBuffersPerformanceTestDesktop/bench.swift' has been generated.
solid:FlatBuffersSwift jocke$ 

```

Generated code is:

```
// generated with FlatBuffersSchemaEditor https://github.com/mzaks/FlatBuffersSchemaEditor

public enum Enum : Int16 {
    case Apples, Pears, Bananas
}
public struct Foo : Scalar {
}
public func ==(v1:Foo, v2:Foo) -> Bool {
    return 
}
public struct Bar : Scalar {
    public var parent : Any /* unsupported struct field type */
    public var time : Int32
    public var ratio : Float32
    public var size : UInt16
}
public func ==(v1:Bar, v2:Bar) -> Bool {
    return  v1.parent==v2.parent &&  v1.time==v2.time &&  v1.ratio==v2.ratio &&  v1.size==v2.size
}
public final class FooBar {
    public var sibling : Bar? = nil
    public var name : String? = nil

```

**Comment by mzaks** [comment]
Ops I forgot about the type :)
As I sad not tested yet ... can fix in a couple of minutes

**Comment by mzaks** [comment]
Now nested structs should be fixed

**Comment by mzaks** [comment]
btw. structs has to be very fast, as there is no decoding involved. It is just a `memcpy`. Memory alignment is equal in FlatBuffers struct and Swift struct. This is why FlatBufferStruct support only scalars as fields. It becomes basically an array of scalars with variable item length.

**Comment by hassila** [comment]
Still no go:

```
solid:FlatBuffersSwift jocke$ java -jar ./fbsCG.jar -fbs FlatBuffersPerformanceTestDesktop/bench.fbs -out FlatBuffersPerformanceTestDesktop/bench.swift -lang swift -lib exclude
ERROR (org.eclipse.xtext.diagnostics.Diagnostic.Syntax) 'mismatched input 'id' expecting '}'' on Struct maxim.zaks.flatBuffers.impl.StructImpl@3a45c42a (name: Foo), lineNumber 25, length 2

'FlatBuffersPerformanceTestDesktop/bench.swift' has been generated.
solid:FlatBuffersSwift jocke$ 

```

Are the swift structure layout well defined then (including padding rules) so one can be sure of this after implementing the padding of flat buffers?

**Comment by mzaks** [comment]
The padding seems to be equal using `strideOf`gives the length of the struct with padding.
I could generate the structs by renaming `id` to `i_d` seems like there is some weird side effect in the XText parser. I will have a look later. #33

**Comment by hassila** [comment]
Ok! Now it seems to work, nice!
