### ISSUE TITLE
Suspected retain cycle in lists / LazyVectors

### ISSUE THREAD

**Issue by hassila** [mzaks/FlatBuffersSwift#21]
To reproduce, run Leaks profile in Instruments on the google performance test - it has a list that triggers the cycle. See attached screenshot.
<img width="1271" alt="cycle" src="https://cloud.githubusercontent.com/assets/8501048/14896645/fdac37dc-0d7e-11e6-8aba-f7c86f0a61af.png">

**Comment by mzaks** [comment]
I actually removed the `values` from `LazyVector` because of the performance reasons.
https://github.com/mzaks/FindCityFB/blob/master/FindCityFB/cityList.swift#L658
In this example initialising LazyVector with over 3 million entries was a bit slow :)
It is not in the main project yet. I will push it soon, this will also fix the Bug I guess.

**Comment by hassila** [comment]
Cool. Looking forward to try it out!

**Comment by hassila** [comment]
FYI, I just gave it a spin and it seems to have eliminated that issue at a first glance (now 300MB instead of 1.1GB RAM top usage, so something still lurks though...) - also a small nice performance improvement for the lazy test benchmark for 1M items:

```
6697 ms decode+use+dealloc
—>
6296 ms decode+use+dealloc
```

**Comment by hassila** [comment]
Ok, checking more carefully, there seems to be one more cycle in the Lazy access generated code, needs "[weak self] in" added to not capture self AFAIU:

```
        public lazy var list : LazyVector<FooBar.LazyAccess> = { 
            let vectorOffset : Offset? = self._reader.getOffset(self._objectOffset, propertyIndex: 0)
            let vectorLength = self._reader.getVectorLength(vectorOffset)
            return LazyVector(count: vectorLength){** [weak self] in**
                FooBar.LazyAccess(reader: self!._reader, objectOffset : self!._reader.getVectorOffsetElement(vectorOffset!, index: $0))
            }

```

With that small fix and the new version of LazyVector, there seem to be no more retain cycles.

It would need to be fixed in the FlatBuffersSchemaEditor code generator though.

After those two fixed, a full run of 1M on the lazy flat bench peaks at 4MB RAM instead of 1.1GB.

**Comment by hassila** [comment]
Looks good now!
