### ISSUE TITLE
Provide better default buffer size to FlatBufferBuilder.init()

### ISSUE THREAD

**Issue by hassila** [mzaks/FlatBuffersSwift#22]
Currently the size is 1 and is doubled each time needed thus requiring a handful of unnecessary malloc/frees for any reasonable normal object - would be nice if the default could be the "sum of the sizes of all scalars, padding, known vtable size, some reasonable guess of N bytes per string" such that normally zero, or just a single reallocation would be needed. 

Each generated class could provide different defaults in the generated code "let builder = FlatBufferBuilder(xxxx)".

**Comment by mzaks** [comment]
This one should be addressed by #6
I think estimating the size would be a tough thing to do, however if you can provide a **serialisation config** this would make everybody happy

**Comment by hassila** [comment]
That would probably be good enough for the most interesting use cases. Perhaps changing the current default from 1 to a reasonable three-digit number (if such a config is not provided) would give better default behavior though (removing 5-10 of the malloc/frees by default). 

One could always use the serialization config to tune it down if desired.

**Comment by mzaks** [comment]
just added 1024*40 as default .. don't ask me why :) but than again the real solution will come later with the config object

**Comment by hassila** [comment]
Btw, the generated code still uses 1 as the default...
