### ISSUE TITLE
Speed up String decoding

### ISSUE THREAD

**Issue by mzaks** [mzaks/FlatBuffersSwift#31]
The new addition seems to speed up the encoding
48ms -> 38ms

but the decoding becomes slower in my measurements:
42ms -> 66ms

**Comment by hassila** [comment]
I think it is a combination of two things: one is the use (or not) of unique strings (I have run with that during latest testing, as I agree with your point that it is a very common use case) so the test suite you have with randomized strings that doesn't use uniquing suffers, the second thing is that it becomes a bit of a tradeoff between decoding and usage (decoding does become more expensive, but usage becomes significantly more inexpensive...).

**Comment by mzaks** [comment]
I had a thought about not decoding strings at all, but have computed getter and settle in the eager implementation. This way user pays the cost of decoding only when s/he needs it and can still set strings or even `StaticString` which is much faster to encode.

**Comment by hassila** [comment]
That could be nice, but one caveat is the need for keeping a copy of the raw data around until decoding is needed (to be able to reuse readers) - but could possibly be worthwhile.

**Comment by hassila** [comment]
Another minor point btw, as you randomize the input data for the contact list benchmark, there is a fair amount of fluctuation between runs built in (doesn't impact what was discussed above) - just wanted to point it out, as it may mislead at times - perhaps can provide some seed to the random number generator to get reproducible test data to eliminate that at some point.

**Comment by mzaks** [comment]
this is a good point even though from everything I saw, the deviation felt not that high.

**Comment by mzaks** [comment]
for now just reverted to the previous Reader implementation of `getString`
Resulted in

77.10 -> 40.89 ms decoding

But it still worth investigating if String decoding can be improved
