### ISSUE TITLE
Retain cycle

### ISSUE THREAD

**Issue by hassila** [mzaks/FlatBuffersSwift#36]
Seems https://github.com/mzaks/FlatBuffersSwift/issues/21 is back...
<img width="983" alt="cycle" src="https://cloud.githubusercontent.com/assets/8501048/14995562/af191d24-1175-11e6-9deb-6520c0cbeaec.png">

**Comment by hassila** [comment]
Reproduces during flat bench lazy run.

**Comment by mzaks** [comment]
Yeah it is funny how with memory leak the Lazy run dealloc is 9 ms and without 910 ms. Makes me wonder if somehow pooling all Table classes and Lazy accessors is a good idea.

**Comment by mzaks** [comment]
Hm ... I remember now why I reintroduced the bug. if I have this

```
LazyVector(count: vectorLength){ [unowned self] in
```

`FlatBuffersGeneratedAPITest` doesn't work anymore ...

**Comment by mzaks** [comment]
Ok, solved it.

**Comment by hassila** [comment]
Looks good now.

> Makes me wonder if somehow pooling all Table classes and Lazy accessors is a good idea

#39
