### ISSUE TITLE
Codegen should support structs as root type

### ISSUE THREAD

**Issue by hassila** [mzaks/FlatBuffersSwift#41]
I believe the scheme must have a root object that is a table?

It would be nice to optionally generate a struct also for the top level for small payload messages where by value semantics would be desirable. An option for the codegen to generate a struct for the root object would be nice to support this.

**Comment by mzaks** [comment]
I also thought about it, but it would be not compatible with Googles FlatBuffers

**Comment by hassila** [comment]
I just read the doc a bit more carefully, the root_type can actually be a struct, so this should "just work".

**Comment by hassila** [comment]
Unfortunately, it didn't. Using a struct as the root_type:

```
solid:FlatBuffersSwift jocke$ java -jar ./fbsCG.jar -fbs test.fbs -out test.swift -lang swift -lib exclude
ERROR (org.eclipse.xtext.diagnostics.Diagnostic.Linking) 'Couldn't resolve reference to Table 'Foo'.' on RootType maxim.zaks.flatBuffers.impl.RootTypeImpl@10b892d5, lineNumber 6, length 3

'test.swift' has been generated.

```

Using test.fbs:

```
struct Foo { // changing to table and it works
  prefix:byte;
  length:uint;
}

root_type Foo;

```

**Comment by hassila** [comment]
Btw, why "I also thought about it, but it would be not compatible with Googles FlatBuffers" ?

I did a struct proposal in #46 - should work or am I missing something?

(sorry, a bit of topic as this issue now about supporting structs as top level objects)

**Comment by mzaks** [comment]
What I mean is that `flatc` returns `sample1.fbs:18:0: error: root type must be a table`
when I try to compile following example

```
struct S2 {
    b1 : bool;
    i1 : int;
}

struct S1 {
    f1 : float;
    s2 : S2;
    d1 : double;
    f2 : float;
    f3 : float;
}

table T1 {
    s : S1;
}

root_type S1;
```

`flatc` does not support structs as root type. I can make `fbsCG` support it, but than it will be a breaking change. We have to clarify it with Google if they would like to support it as well.

**Comment by hassila** [comment]
Ok, not very important in view of the planned reader improvements.

**Comment by hassila** [comment]
Although I think it is a problem with flatc. The documentation seem to expect it to work...

https://google.github.io/flatbuffers/flatbuffers_guide_writing_schema.html

**Comment by mzaks** [comment]
Btw. you can just take the generated stark classes and convert them to binary as they are. This will achieve the expected effect.
