### ISSUE TITLE
Review and summary of thread safety of pooling

### ISSUE THREAD

**Issue by hassila** [mzaks/FlatBuffersSwift#44]
Ok, I had a look at the thread safety of the current pooling - and its a mixed bag...
1. Currently the reader&builder pools are not safe to be used from multiple threads - tried to fix it and added the most lightweight synchronization I could find (objc_sync_enter/exit) and it has a significant impact on the streaming test. 

Pooling is still clearly beneficial, but if adding the sync, it is a definite issue hampering performance.
1. The general instance pools are safe to be used from one thread per instance-type (that is, if one had two different .fbs they could be used in parallel from two threads, as the caches are separated per type) - but it is in general the same issue as above

**To summarize**
Enabling the pooling has a significant improvement for single-thread usage
Adding naive synchronization kills much, but not all of the advantage of using builder&reader pools
Adding it seems to completely kill table instance pool improvements

**Next steps**
1. Can address it either by documenting allowed usage of pooling (with more formal constraints on what is allowable and possibly looking at restructuring/alternate API). 
2. Alternatively, we can add synchronization and always be safe (but significantly slower). 
3. Thirdly, we could have two possible modes so one must explicitly enable multi-thread mode.

I'll see if I can find any more suitable solutions but would be interesting to hear your thoughts @mzaks.

I would probably personally lean toward 1 or 3 (or a combination thereof), as pooling is opt-in, one can always choose not to use it - for those applications that only access the data model from the .fbs from one thread, it really does help, but I think it is important that the out of the box behavior is safe but one can opt in.

**Comment by hassila** [comment]
Cleaned up reader&builder usage in #45 - thread safe by default, but now we have reusable builder and reader API:s which can be used when performance is paramount. The major consideration is really table instance pooling.

**Comment by mzaks** [comment]
I think we solving the wrong problem here.
I looked at the performance benchmarks from `flatcc` which is the C port and it runs decoding/traversing in 29 ms. 
https://github.com/dvidelabs/flatcc#benchmark
First I could not believe it so I downloaded it and tried it myself. I got 26 ms on my machine :)
So what I did is I wrote following functions

``` swift
func getListCountFrom(reader : FlatBufferReader, fooBarContainerOffset : Offset) -> Int {
    let offset_list : Offset? = reader.getOffset(fooBarContainerOffset, propertyIndex: 0)
    return reader.getVectorLength(offset_list)
}

func getFooBarOffsetFrom(reader : FlatBufferReader, fooBarContainerOffset : Offset, listIndex : Int) -> Offset {
    let offset_list : Offset? = reader.getOffset(fooBarContainerOffset, propertyIndex: 0)
    return reader.getVectorOffsetElement(offset_list!, index: listIndex)!
}

func getInitializedFrom(reader : FlatBufferReader, fooBarContainerOffset : Offset) -> Bool {
    return reader.get(fooBarContainerOffset, propertyIndex: 1, defaultValue: false)
}
func getFrootFrom(reader : FlatBufferReader, fooBarContainerOffset : Offset) -> Enum {
    return Enum(rawValue: reader.get(fooBarContainerOffset, propertyIndex: 2, defaultValue: Enum.Apples.rawValue))!
}
func getLocationFrom(reader : FlatBufferReader, fooBarContainerOffset : Offset) -> UnsafeBufferPointer<UInt8> {
    return reader.getStringBuffer(reader.getOffset(fooBarContainerOffset, propertyIndex: 3))!
}
func getSiblingFrom(reader : FlatBufferReader, fooBarOffset : Offset) -> Bar {
    let result : Bar = reader.get(fooBarOffset, propertyIndex: 0)!
    return result
}
func getNameFrom(reader : FlatBufferReader, fooBarOffset : Offset) -> UnsafeBufferPointer<UInt8> {
    return reader.getStringBuffer(reader.getOffset(fooBarOffset, propertyIndex: 1))!
}
func getRatingFrom(reader : FlatBufferReader, fooBarOffset : Offset) -> Float64 {
    let result : Float64 = reader.get(fooBarOffset, propertyIndex: 2)!
    return result
}
func getPostfixFrom(reader : FlatBufferReader, fooBarOffset : Offset) -> UInt8 {
    let result : UInt8 = reader.get(fooBarOffset, propertyIndex: 3)!
    return result
}
```

Which let us get the values without having any objects, except for the reader.
And added following function in `flatbench`:

``` swift
func flatDecodeDirect(data : UnsafeMutablePointer<UInt8>, _ dataCount:Int) -> Int{
    let reader = FlatBufferReader.create(data, count: dataCount, config: readConfiguration)
    let fooBarContainerOffset = reader.rootObjectOffset

    var sum:Int = 1

    sum = sum + Int(getLocationFrom(reader, fooBarContainerOffset: fooBarContainerOffset).count)
    sum = sum + Int(getFrootFrom(reader, fooBarContainerOffset: fooBarContainerOffset).rawValue)
    sum = sum + (getInitializedFrom(reader, fooBarContainerOffset: fooBarContainerOffset) ? 1 : 0)

    for i in 0..<getListCountFrom(reader, fooBarContainerOffset: fooBarContainerOffset) {
        let foobarOffset = getFooBarOffsetFrom(reader, fooBarContainerOffset: fooBarContainerOffset, listIndex: i)
        sum = sum + Int(getNameFrom(reader, fooBarOffset: foobarOffset).count)
        sum = sum + Int(getPostfixFrom(reader, fooBarOffset: foobarOffset))
        sum = sum + Int(getRatingFrom(reader, fooBarOffset: foobarOffset))

        let bar = getSiblingFrom(reader, fooBarOffset: foobarOffset)

        sum = sum + Int(bar.ratio)
        sum = sum + Int(bar.size)
        sum = sum + Int(bar.time)

        let foo = bar.parent
        sum = sum + Int(foo.count)
        sum = sum + Int(foo.i_d)
        sum = sum + Int(foo.length)
        sum = sum + Int(foo.prefix)
    }

    FlatBufferReader.reuse(reader)

    return sum
}
```

this gives me now 99 ms compared 569 ms decode+use+dealloc in Eager run.
I think if I inline the reader in the ugly accessor functions, than we might get even very close to C speed.

So what I think is, in scenarios where speed is the most important criteria, the user should take the bullet and use the cumbersome API. This API is completely functional and needs no complex thread handling. The nice API is not thread safe, we can keep the instance pooling for the reader and builder, but I guess it is better to remove it from the Table classes as it complicates things a lot.

**Comment by mzaks** [comment]
I just pushed the implementation of direct decoding and traversal without Reader. I get 0.342 ms
@hassila could you please check if I am not doing something stupid :)

**Comment by mzaks** [comment]
I actually didn't believed my eyes, but it seems to be correct. We are 60 times faster than C and C++ :)

**Comment by hassila** [comment]
Very interesting, I will have a deeper look (may only be tomorrow though).

Just as a reference, the C++ decode looks like this:

```
  int64_t Use(void *decoded) {
    auto foobarcontainer = GetFooBarContainer(decoded);
    sum = 0;
    Add(foobarcontainer->initialized());
    Add(foobarcontainer->location()->Length());
    Add(foobarcontainer->fruit());
    for (unsigned int i = 0; i < foobarcontainer->list()->Length(); i++) {
      auto foobar = foobarcontainer->list()->Get(i);
      Add(foobar->name()->Length());
      Add(foobar->postfix());
      Add(static_cast<int64_t>(foobar->rating()));
      auto bar = foobar->sibling();
      Add(static_cast<int64_t>(bar->ratio()));
      Add(bar->size());
      Add(bar->time());
      auto &foo = bar->parent();
      Add(foo.count());
      Add(foo.id());
      Add(foo.length());
      Add(foo.prefix());
    }
```

Just one thought - perhaps we want to try using a generating a struct with nice access through computed properties - this could possibly give the best of two worlds - something along the lines of  

```
struct FooBar {
    buffer : UnsafePointer<UInt8>
    myOffset : Int = 0
    var name: UnsafeBufferPointer<UInt8> { get { return getStringBuffer(buffer, getOffset(buffer, myOffset, propertyIndex: 1))! } }
    var rating: Float64 { get { return get(buffer, myOffset, propertyIndex: 2)! } }
    var postfix: UInt8 {  get { return get(buffer, myOffset, propertyIndex: 3)! } }
}

```

I would expect it to give similar performance? Still, I think you are right in that it is time to take a step back :)

**Comment by hassila** [comment]
https://github.com/mzaks/FlatBuffersSwift/pull/46 show a working prototype of the struct approach, please have a look.

**Comment by hassila** [comment]
(spoiler: It is even slightly faster than the direct decoding in my testing :)

**Comment by mzaks** [comment]
Hm, to be honest I am surprised. I used struct as it is because than it is just a memory copy, but I guess it has to be retained and released anyways.

**Comment by mzaks** [comment]
Ach ok I misunderstood what you meant with the struct approach :)

This looks good and the API is much better.

**Comment by mzaks** [comment]
Created #49 to move the conversation into more suitable thread

**Comment by hassila** [comment]
About the various pools:
1. The reader pool should go away due to #49 
2. The builder pool could be kept to help **toByteArray**, but it could be removed for simplification if desired, as we have the **toFlatBufferBuilder** and access to **builder._dataStart**/**builder._dataCount** which allows for external reuse of builders if performance really matters. 
3. The table pools should probably go as you suggest - I saw that some other languages actually support them (Java / Go IIRC) in other flat buffers implementations though, so we probably should remeasure some more realistic use cases (with added synchronization to make the pool thread safe as for the builder/reader pools) before finally deciding

**Comment by hassila** [comment]
Wrt 3. I made the table pools thread safe and remeasured eager in https://github.com/mzaks/FlatBuffersSwift/pull/60 - seems worthwhile to keep them in (they are opt-in anyway) .

**Comment by hassila** [comment]
Ok, the current state is that all pools now are thread-safe, lets open new issues if we want to remove anything in the future. 

We should carefully document on how to use the table object pool facilities when wrapping things up (specifically that one should only try to return an object to the pool when one is a) fairly sure that one is the only one holding a reference (no worries if one isn't, the code is robust for that, just unnecessary trying to pool in that case as it would be overhead) b) one is absolutely sure that one will drop a reference when exiting scope or by reassignment )
