### ISSUE TITLE
Union types support for type introspection

### ISSUE THREAD

**Issue by hassila** [mzaks/FlatBuffersSwift#52]
As uncovered in #50 - it should be possible to inspect what type a union contains for proper casting.

**Comment by mzaks** [comment]
I would rather use type pattern matching for that (switch statement)
Like this:

``` swift
func foo(o : Address){
    switch o {
    case let s as PostalAddress:
        print(s.city)
    case let s as EmailAddress:
        print(s.mailto)
    case let s as WebAddress:
        print(s.url)
    case let s as TelephoneNumber:
        print(s.number)
    default:
        print("implement what to do for forward compatibility")
    }
}
```

**Comment by hassila** [comment]
Ah, I had completely missed that feature (still early Swift days for me) - very nice indeed! Fixed in https://github.com/hassila/FlatBuffersSwift/commit/63eb7fecff6cda178a8676955c86a7f42a57413d
