### ISSUE TITLE
Not able to locate source for the code generator fbsCG.jar

### ISSUE THREAD

**Issue by BenziAhamed** [mzaks/FlatBuffersSwift#56]
Couldn't find this anywhere. Is this available in another repo?

**Comment by mzaks** [comment]
It's in a separate repository:
https://github.com/mzaks/FlatBuffersSchemaEditor

However I haven't committed the latest changes, because currently I am moving fast and broke some UnitTests. Will commit the changes when everything got stable.

**Comment by BenziAhamed** [comment]
Ah, thanks. I'll check it out later then.
