### ISSUE TITLE
Builder must add zero termination to strings

### ISSUE THREAD

**Issue by hassila** [mzaks/FlatBuffersSwift#63]
According to [the flatbuffers internals](http://google.github.io/flatbuffers/flatbuffers_internals.html) all strings should be C-style zero terminated - we should append that in createString/createString/createStaticString for compatibility.

**Comment by mzaks** [comment]
This is the most confusing doc ever :)

> Strings are simply a vector of bytes, and are always null-terminated. Vectors are stored as contiguous aligned scalar elements prefixed by a 32bit element count (not including any null termination). Neither is stored inline in their parent, but are referred to by offset.

Is it **null-terminated** or is it **not including any null termination** 🙃
I personally would not include null termination because of the count prefix. However #62 will add some padding to the end of the string.

**Comment by hassila** [comment]
It would be null terminated but the count does not include the terminator (i.e. It is strlen()). 

I would assume that choice is to let c based languages access the buffer directly while the length actually makes sense to everyone else ;-)

I had a look at the Java implementation and they added a null byte at the end.

**Comment by mzaks** [comment]
OK that makes sense.

**Comment by mzaks** [comment]
Now `BinaryBuildConfig` has a `nullTerminatedUTF8` option. It is an option because it slows down encoding process, and only needed for C and C++ compatibility. If you know that your binary will not be decoded by C or C++ clients, keep it turned off.
