### ISSUE TITLE
Change LazyAccess to FileAccess

### ISSUE THREAD

**Issue by mzaks** [mzaks/FlatBuffersSwift#64]
This implies that we have a FlatBuffersFileReader and FileAccess classes which use them.
They are not fast but they let users access data in huge binary files without loading them into memory.

**Comment by hassila** [comment]
Just mmap of the file and use the streaming or eager interfaces as needed, or something else?

**Comment by mzaks** [comment]
I used `NSFileHandle` works as a charm. I see it more for a use case where you have a big config and want to read portions of it. It is much slower than even what we got with previous LazyAccess, but in such scenario this doesn't matter much.

**Comment by hassila** [comment]
You might want to give NSData with mmap a shot also and see if it is beneficial - 

E.g. something along the lines:
`NSData *data = [NSData dataWithContentsOfFile:path options:NSDataReadingMappedIfSafe error:&error];`

**Comment by hassila** [comment]
(Swiftified of course)

**Comment by mzaks** [comment]
Swift3 version has two `FBReader` implementations. `FBMemoryReader` and `FBFileReader`.
This way when using `from(reader : FBReader)` API on root table class or `_Direct` struct user can chose from which source the data is loaded.
