### ISSUE TITLE
Migrate to Swift 3

### ISSUE THREAD

**Issue by hassila** [mzaks/FlatBuffersSwift#65]
How would you like to approach this, using a branch, or simply going ahead in master? 

Expecting new shiny tools tomorrow due to WWDC...

Personally, I wouldn't mind migrating to S3 in master as things are still a bit in flux (and preferably looking at support for the package manager), but doing a swift3 branch is also more than completely fine of course. Thoughts?

Also related to #55.

**Comment by mzaks** [comment]
Totally agree on that. I will just tag the latest Swift 2.2 version.
Only if someone is using FlatBuffersSwift in production and don't want to migrate to Swift 3.
In this case people should approach me directly. It is always possible to make a branch from a Tag.

**Comment by hassila** [comment]
Ok, cool. Do you want help with this one? I can create a PR and you can tag the 2.2 rev. before merging in that case.

**Comment by mzaks** [comment]
Is S3 already stable? I would rather wait a bit. Other wise the master will be in constant refactoring mode.

**Comment by hassila** [comment]
It's probably not stable enough yet - looking at https://swift.org/blog/swift-3-0-release-process/ - when swift-3.0-branch is created, it should be good enough to work against with need to refactor as the feature set would be frozen. Let's see what the timeline becomes (not communicated yet).

Another alternative would be to track the swift-3.0-preview-<X>-branch:es and refactor (if needed...) every 6 weeks or so, each such refactor would likely be a smaller chunk of work.

**Comment by mzaks** [comment]
Hm in this case a separate branch makes more sense I guess, because people who want to try out FlatBuffersSwift can do it from master. Advanced users who are already playing around with S3 will be able to find out about the branch :)

**Comment by gaveezy** [comment]
will you support Swift 3 soon?

**Comment by mzaks** [comment]
Yes, now as it is officially released I will put as high priority. I reserved couple of days for this project next week, hopefully it will be enough to have the first swift 3 version.
I am optimistic 😬

**Comment by notscimmy** [comment]
Any update on the progress of the Swift 3 upgrade?

**Comment by kwestlund** [comment]
I am also eagerly awaiting the Swift3 upgrade:)

**Comment by mzaks** [comment]
Ok was a bit to optimistic before. Will need a couple more weeks. Sorry.

**Comment by kwestlund** [comment]
No problem, thanks for your work.  I'm building a game with Java servers that use flatbuffers and really needed your swift library on the client side, so appreciate it very much.

Ken

**Comment by johndpope** [comment]
@mzaks why not draft an official swift3 fork - people can pick up from you and upgrade code.

**Comment by mzaks** [comment]
FlatBuffersSwift ported to Swift3. 🎉
I also cleaned it up a bit.
In this repository I keep only the lib and the UnitTests.
Performance tests now have there own home.
https://github.com/mzaks/FlatBuffersSwiftPerformanceTest
Btw. with Swift3 we are a bit slower again. Everyone is welcome to make make pull requests ;)
Also I don't use Swift3 in production yet. 
If you generate your schemas and there are some problems, please let me know.

**Comment by hassila** [comment]
Nice, good job! Will be some time before I will be able to give feedback due to other commitments, but looking forward to trying it out, thanks!
