### ISSUE TITLE
Generated code is not valid from schemas w/ scalar array

### ISSUE THREAD

**Issue by tamastimar** [mzaks/FlatBuffersSwift#79]
Hi, given the following schema:
```
table List {
  people : [Person];
}

table Person {
  firstName : string;
  lastName : string;
  luckyNumbers : [int];
}

root_type List;
```
From that the generated Swift 3 code can't be compiled. It's because getVectorScalarElement method (which reads the int array) returns an optional but the caller method expects an unwrapped type. So unwrapping/nil cases are not handled.

In the Swift 2.3 branch it has worked well.

Could you recommend any solution? Thanks!

**Comment by mzaks** [comment]
Hi Tamas,

thank you for reporting I will add such case to unit tests and solve the problem ASAP.
Meanwhile if it is urgent for you, you would have to fix the generated code manually.

I hope to provide the fix today.

**Comment by mzaks** [comment]
Just pushed a version which improves the way Vectors are handled in FlatBuffersSwift.
The generated code has however slightly different API.

**Comment by tamastimar** [comment]
@mzaks thanks for the fast feedback. 👍 

After pulling the updated generator the output contains two undeclared types (`FlatBuffersDirectAccess`, `FlatBuffersTableVector`) so still can't be compiled.

Am I doing something wrong? 🤔

**Comment by mzaks** [comment]
Sorry forgot to update the FlatBuffersReader in the code generator. Should be fixed now.

**Comment by tamastimar** [comment]
Thanks for the help, really appreciate!
