### ISSUE TITLE
Java source

### ISSUE THREAD

**Issue by jnordberg** [mzaks/FlatBuffersSwift#81]
Is the java source available somewhere? I was going to have a stab at #10 but don't see where to start

**Comment by mzaks** [comment]
Have a look here https://github.com/mzaks/FlatBuffersSchemaEditor

It is a Xtext based project, let me know if you need some getting started help.

**Comment by jnordberg** [comment]
Thanks, I managed to get it up and running, I'll create a PR over there with my attempt at implementing the required attribute.
