### ISSUE TITLE
Swift Apr is faster than C?

### ISSUE THREAD

**Issue by proyb6** [mzaks/FlatBuffersSwift#83]
APR uses in Swift is Apache Portable Runtime
https://apr.apache.org/

Swift binary tree appear to use APR so does C and C++ in these benchmark.
http://benchmarksgame.alioth.debian.org/u64q/swift.html
http://benchmarksgame.alioth.debian.org/u64q/measurements.php?lang=gcc

**Comment by mzaks** [comment]
Not sure I understand what this issue suppose to be about.

**Comment by proyb6** [comment]
It uses APR to manage unsafe pointer, which could help to speed up in your benchmark you have compared to C before.

http://benchmarksgame.alioth.debian.org/u64q/program.php?test=binarytrees&lang=swift&id=9

**Comment by mzaks** [comment]
Hello again and sorry for the late response.
For me the benchmark was about having a watermark, how far I can push the implementation in regards of performance. It was never about the benchmark itself, nor was it about winning against C implementation.

Specialised runtime to beat C defeats a bit the purpose, as I will not be able to run APR on iDevices and probably also not on Macs. It might run on Linux distributions, and this is great but this is on the shoulders of developer, who operates FlatBuffersSwift on Linux. If it runs faster on APR it basically, proves that APR is great, but does not show me where I can tune FlatBuffersSwift.
