### ISSUE TITLE
Allow using secondary type names in schemas

### ISSUE THREAD

**Issue by eduardbosch** [mzaks/FlatBuffersSwift#87]
Hi,

I've found that the FlatBuffersSchemaEditor does not support the secondary type names in the schemas. By secondary names I mean the names in parenthesis in the types section here https://google.github.io/flatbuffers/flatbuffers_guide_writing_schema.html

I had a schema that used `uint8` and I had to change it to `ubyte` in order to compile.

Would be nice to support all types.

Thanks

**Comment by mzaks** [comment]
Hi Eduard thanks for reporting. How time critical is the fix for you?

**Comment by eduardbosch** [comment]
It's not really important, as I've compiled my scheme changing the type names. I've reported it only as an enhancement that would be nice to have 😉

**Comment by mzaks** [comment]
I introduced new code generator written in Swift which supports secondary type names.
https://github.com/mzaks/FlatBuffersSwiftCodeGen
@eduardbosch please let me know if you have any issues with the new code generator
