### ISSUE TITLE
Contributing WASI support

### ISSUE THREAD

**Issue by oxcug** [mzaks/FlatBuffersSwift#95]
I've made some small changes (e.g deleting strenuous `import Foundation` calls and other small changes) to make this library compatible with the swift wasi compiler. @mzaks would you consider accepting those changes upstream?

**Comment by mzaks** [comment]
Hi @oxcug feel free to create a PR.

**Comment by oxcug** [comment]
@mzaks Will do, I imagine it's best to push to the google flatbuffer repo? Or should I make the change to this one?

**Comment by mzaks** [comment]
@oxcug I would recommend to make a PR on the official Google Repo.

**Comment by oxcug** [comment]
Gotcha, will make a PR and tag you. Expect a PR soon.
